### ISSUE TITLE
Invalid string auto_group_enrol_form_no_group_found

### ISSUE THREAD

**Issue by mudrd8mz** [pascal-my/moodle-admin_tool_groupautoenrol#2]
The string auto_group_enrol_form_no_group_found must not contain the concatenation operator and compute the value on real time. Things like that do not work wit other language pack provided via AMOS.

Please fix to something like

```
$string['auto_group_enrol_form_no_group_found'] = 'You must <a href="{$a->url}">create groups</a> first !';
```

Or even better make it without the embedded link, just something like

```
$string['auto_group_enrol_form_no_group_found'] = 'Create groups first';
```

and use it all as a link text in the code (more friendly for translators).

**Comment by germanvaleroelizondo** [comment]
Hi,
English language strings are not yet available for translation in AMOS :(  Please fix as suggested by mudrd8mz .

**Comment by pascal-my** [comment]
Hi guys,
I fixed it ! Thanks you !

**Comment by germanvaleroelizondo** [comment]
Thanks a lot. 
I have already translated it (today) to my language pack (Mexican Spanish).
